import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { randomUUID, createHash } from 'node:crypto';
test('schema migration, acquisition, eligibility, concurrency and isolation', async () => {
    const db = new PGlite();
    try {
        const schema = fs.readFileSync('tests/fixtures/production-schema.sql', 'utf8');
        const constraints = schema.match(/^alter table public\..* add constraint .*;$/gm) || [];
        await db.exec(schema.replace(/^alter table public\..* add constraint .*;$/gm, '') + '\n' + constraints.sort((a, b) => Number(a.includes('FOREIGN KEY')) - Number(b.includes('FOREIGN KEY'))).join('\n'));
        // PGlite cannot run pg_cron: record the real migration's scheduling call.
        await db.exec(`create schema cron;
          create table cron.job(jobname text primary key,schedule text,command text,jobid bigint default 1,active boolean default true);
          create function cron.alter_job(bigint,active boolean) returns void language sql as $$
            update cron.job set active=$2 where jobid=$1 $$;
          create function cron.schedule(text,text,text) returns bigint language sql as $$
            insert into cron.job(jobname,schedule,command) values($1,$2,$3) on conflict(jobname) do update
            set schedule=excluded.schedule,command=excluded.command returning 1::bigint $$;`);
        await db.exec(fs.readFileSync('supabase/migrations/20261009151423_acquisition_activation_measurement.sql', 'utf8'));
        const query = (s, args = []) => db.query(s, args);
        const one = async (s, args = []) => (await query(s, args)).rows[0];
        const token = 'a'.repeat(64), hash = createHash('sha256').update(token).digest('hex');
        const visitor = randomUUID(), session = randomUUID(), user = randomUUID();
        const arrival = async (kind, touch, s = session) => query('select public.record_acquisition_arrival($1,$2,$3,$4,$5,$6)', [hash, visitor, s, randomUUID(), kind, touch]);
        await arrival('landing', { utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'first', channel: 'paid_search', landing_path: '/' });
        await arrival('landing', { utm_source: 'duplicate', channel: 'paid_search' });
        await arrival('landing', { channel: 'direct' }, randomUUID());
        assert.equal((await one('select latest_non_direct from ff_measurement.journeys')).latest_non_direct.utm_campaign, 'first');
        await arrival('landing', { utm_source: 'newsletter', utm_campaign: 'later', channel: 'email' }, randomUUID());
        await arrival('signup_started', { channel: 'direct' });
        await query('insert into auth.users(id,email,raw_user_meta_data) values($1,$2,$3)', [user, 'owner@example.test', { ff_setup: { business_name: 'Fixture', owner_name: 'Owner', location_name: 'Front', journey_token: token } }]);
        await query("select set_config('request.jwt.claim.sub',$1,false)", [user]);
        await assert.rejects(query('select public.complete_acquisition_signup()'), /Confirmed/);
        await query('update auth.users set email_confirmed_at=now() where id=$1', [user]);
        const setup = (await one('select public.complete_acquisition_signup() as result')).result;
        assert.equal(setup.business.name, 'Fixture');
        const repeated = await Promise.all([one('select public.complete_acquisition_signup() as result'), one('select public.complete_acquisition_signup() as result')]);
        assert.ok(repeated.every(x => x.result.business.id === setup.business.id));
        assert.equal((await one('select count(*)::int n from public.businesses')).n, 1);
        const acquired = await one('select * from ff_measurement.business_acquisition');
        assert.equal(acquired.first_touch.utm_campaign, 'first');
        assert.equal(acquired.latest_non_direct.utm_campaign, 'later');
        const b = setup.business.id, l = setup.location.id;
        await query("insert into analytics_events(business_id,location_id,event_type,source) values($1,$2,'qr_generated','qr')", [b, l]);
        await query("insert into analytics_events(business_id,location_id,event_type,source) values($1,$2,'qr_deployed','print')", [b, l]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='placement_confirmed'")).n, 0);
        const visit = randomUUID();
        await query('select record_feedback_page_open($1,$2,$3,false)', [l, visit, user]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='feedback_page_open'")).n, 0);
        const customer = randomUUID();
        await query('select record_feedback_page_open($1,$2,null,false)', [l, customer]);
        await query('select record_feedback_page_open($1,$2,null,false)', [l, customer]);
        assert.equal((await one('select count(*)::int n from ff_measurement.page_opens')).n, 2);
        await query('select record_feedback_page_open($1,$2,null,true)', [l, customer]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='feedback_page_open'")).n, 0);
        await query('select record_feedback_page_open($1,$2,null,false)', [l, customer]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='feedback_page_open'")).n, 0, 'a retry cannot unmark a declared test');
        await query('select record_feedback_page_open($1,$2,null,false)', [l, randomUUID()]);
        await db.exec(`select set_config('request.jwt.claims','{"role":"service_role"}',false)`);
        await query("insert into feedback(location_id,sentiment,measurement_status) values($1,'happy','staff_test')", [l]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='eligible_feedback'")).n, 0);
        const save = key => query("insert into feedback(location_id,sentiment,measurement_status,submission_key) values($1,'happy','eligible_unverified',$2)", [l, key]);
        const submission = randomUUID();
        await save(submission);
        await assert.rejects(save(submission), /unique/);
        await Promise.all([save(randomUUID()), save(randomUUID())]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='eligible_feedback'")).n, 1);
        for (let i = 0; i < 3; i++)
            await query("insert into feedback(location_id,sentiment,device_key,measurement_status) values($1,'happy','repeat-device','eligible_unverified')", [l]);
        assert.ok((await one("select count(*)::int n from ff_measurement.feedback_eligibility where flagged and status='eligible_unverified'")).n > 0, 'flagged responses stay eligible');
        // Provider state fixtures only: no checkout, webhook or real order is sent.
        const order = (await one("insert into qr_print_orders(business_id,location_id,product_type,product_name,prodigi_sku,quantity,delivery_contact,address_line_1,city,postcode,metadata) values($1,$2,'qr_sticker','Fixture','fixture',1,'Fixture','Fixture','Fixture','TEST','{\"integration_environment\":\"sandbox\"}') returning id", [b, l])).id;
        await query("update qr_print_orders set stripe_payment_status='paid',stripe_session_id='fixture-session',fulfilment_status='completed',prodigi_order_id='fixture-provider' where id=$1", [order]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage in ('order_paid','order_fulfilled')")).n, 0, 'sandbox never activates');
        await query("update qr_print_orders set metadata='{\"integration_environment\":\"production\"}',fulfilment_status='needs_attention',prodigi_order_id=null where id=$1", [order]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='order_paid'")).n, 1);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='order_fulfilled'")).n, 0, 'ambiguous provider state is not fulfilment');
        await query("update qr_print_orders set fulfilment_status='completed',prodigi_order_id='fixture-provider' where id=$1", [order]);
        await query("update qr_print_orders set fulfilment_status='completed' where id=$1", [order]);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='order_fulfilled'")).n, 1);
        assert.equal((await one("select count(*)::int n from ff_measurement.milestones where stage='placement_confirmed'")).n, 0, 'even fulfilment is not placement');
        await query("insert into analytics_events(business_id,location_id,event_type) values($1,$2,'onboarding_qr_placed_confirmed')", [b, l]);
        await assert.rejects(query("select acquisition_cohort_report(current_date-1,current_date)"), /Internal admin/);
        await query("insert into internal_admins(user_id,email,role) values($1,'owner@example.test','superuser')", [user]);
        const report = (await one('select acquisition_cohort_report(current_date-1,current_date) result')).result;
        assert.equal(report.businesses.length, 1);
        assert.equal(report.businesses[0].excluded_internal, true);
        assert.equal(report.businesses[0].milestones.eligible_feedback != null, true);
        await db.exec("set role anon");
        await assert.rejects(query('select * from ff_measurement.business_acquisition'), /permission denied/);
        await assert.rejects(query('select record_feedback_page_open($1,$2,null,false)', [l, randomUUID()]), /permission denied/);
        await assert.rejects(query('select complete_acquisition_signup()'), /permission denied/);
        await db.exec('reset role');
        const other = randomUUID();
        await query("insert into auth.users(id,email,email_confirmed_at) values($1,'other@example.test',now())", [other]);
        await query("select set_config('request.jwt.claim.sub',$1,false)", [other]);
        await db.exec("select set_config('request.jwt.claims','{\"role\":\"authenticated\"}',false);set role authenticated");
        await assert.rejects(query("insert into business_users(business_id,user_id,role) values($1,$2,'owner')", [b, other]), /row-level security/);
        await assert.rejects(query("insert into analytics_events(business_id,location_id,event_type) values($1,$2,'qr_generated')", [b, l]), /row-level security/);
        assert.equal((await one('select complete_acquisition_signup() result')).result, null);
        await db.exec('reset role');
        const invited = randomUUID();
        await query("insert into business_invites(business_id,email,token) values($1,'invited@example.test','test-token')", [b]);
        await query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,'invited@example.test',now(),$2)", [invited, { ff_setup: { business_name: 'Not acquisition', owner_name: 'Invite' } }]);
        assert.equal((await one('select count(*)::int n from ff_measurement.signup_intents where user_id=$1', [invited])).n, 0);
        await query('update auth.users set raw_user_meta_data=$2 where id=$1', [other, { ff_setup: { business_name: 'Not acquisition', owner_name: 'Existing' } }]);
        assert.equal((await one('select count(*)::int n from ff_measurement.signup_intents where user_id=$1', [other])).n, 0, 'editing metadata on an existing user cannot mint acquisition');
        const lateUser = randomUUID(), lateToken = 'b'.repeat(64), lateHash = createHash('sha256').update(lateToken).digest('hex');
        await query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,'late@example.test',now(),$2)", [lateUser, { ff_setup: { business_name: 'Retry', owner_name: 'Late', journey_token: lateToken } }]);
        await query("select set_config('request.jwt.claim.sub',$1,false)", [lateUser]);
        const lateSetup = (await one('select complete_acquisition_signup() result')).result;
        await query('select record_acquisition_arrival($1,$2,$3,$4,$5,$6,$7)', [lateHash, randomUUID(), randomUUID(), randomUUID(), 'landing', { channel: 'email', utm_source: 'recovered' }, lateUser]);
        assert.equal((await one('select first_touch from ff_measurement.business_acquisition where business_id=$1', [lateSetup.business.id])).first_touch.utm_source, 'recovered');
        await query('select record_acquisition_arrival($1,$2,$3,$4,$5,$6,$7)', [lateHash, randomUUID(), randomUUID(), randomUUID(), 'landing', { channel: 'email', utm_source: 'overwrite' }, other]);
        assert.equal((await one('select first_touch from ff_measurement.business_acquisition where business_id=$1', [lateSetup.business.id])).first_touch.utm_source, 'recovered');
        const limits = await query("select measurement_rate_limit('fixture',2) ok from generate_series(1,3)");
        assert.deepEqual(limits.rows.map(x => x.ok), [true, true, false]);
        await db.exec("set role authenticated");
        await query("insert into analytics_events(business_id,location_id,event_type,source) values($1,$2,'qr_generated','business_dashboard')", [lateSetup.business.id,lateSetup.location.id]);
        await assert.rejects(query("insert into analytics_events(business_id,location_id,event_type) values($1,$2,'qr_print_order_paid')", [lateSetup.business.id,lateSetup.location.id]), /row-level security/);
        await query("insert into feedback(location_id,sentiment,measurement_status) values($1,'happy','eligible_unverified')", [lateSetup.location.id]);
        await db.exec('reset role');
        assert.equal((await one('select status from ff_measurement.feedback_eligibility where business_id=$1',[lateSetup.business.id])).status,'legacy_unclassified','direct writes cannot forge trusted eligibility');
        await db.exec('set role authenticated');
        await assert.rejects(query('select ff_measurement.cleanup()'), /permission denied/);
        await db.exec('reset role; begin');
        const milestonesBefore = (await query('select * from ff_measurement.milestones order by business_id,location_id,stage')).rows;
        const feedbackBefore = (await one('select count(*)::int n from public.feedback')).n;
        const freshJourney = await one('select * from ff_measurement.journeys where token_hash=$1', [lateHash]);
        await query("update ff_measurement.journeys set created_at=now()-interval '90 days' where token_hash=$1", [hash]);
        await query("update ff_measurement.business_acquisition set acquired_at=now()-interval '90 days',first_touch=first_touch || '{\"gclid\":\"expired\",\"dclid\":\"expired\",\"gbraid\":\"expired\"}',latest_non_direct=latest_non_direct || '{\"wbraid\":\"expired\",\"fbclid\":\"expired\",\"msclkid\":\"expired\"}' where business_id=$1", [b]);
        await query("update ff_measurement.signup_intents set created_at=now()-interval '90 days' where user_id=$1", [user]);
        await query("update ff_measurement.page_opens set received_at=now()-interval '90 days' where visit_id=$1", [visit]);
        await db.exec("insert into ff_measurement.rate_limits(bucket,started_at) values('expired',now()-interval '2 days'),('recent',now()-interval '2 days'+interval '1 second'); select ff_measurement.cleanup(); select ff_measurement.cleanup();");
        assert.equal((await one('select count(*)::int n from ff_measurement.journeys where token_hash=$1', [hash])).n, 0);
        assert.equal((await one('select count(*)::int n from ff_measurement.arrivals where token_hash=$1', [hash])).n, 0);
        assert.deepEqual(await one('select * from ff_measurement.journeys where token_hash=$1', [lateHash]), freshJourney);
        const retained = await one('select * from ff_measurement.business_acquisition where business_id=$1', [b]);
        assert.equal(retained.visitor_id,null);
        assert.equal(retained.first_touch.utm_campaign,'first');
        assert.equal(retained.latest_non_direct.utm_campaign,'later');
        for (const key of ['gclid','dclid','gbraid','wbraid','fbclid','msclkid']) {
            assert.equal(retained.first_touch[key],undefined);
            assert.equal(retained.latest_non_direct[key],undefined);
        }
        assert.equal((await one('select token_hash from ff_measurement.signup_intents where user_id=$1',[user])).token_hash,null);
        assert.equal((await one('select raw_user_meta_data from auth.users where id=$1',[user])).raw_user_meta_data.ff_setup.journey_token,undefined);
        assert.equal((await one('select raw_user_meta_data from auth.users where id=$1',[user])).raw_user_meta_data.ff_setup.business_name,'Fixture');
        assert.equal((await one('select count(*)::int n from ff_measurement.page_opens where visit_id=$1',[visit])).n,0);
        assert.ok((await one('select count(*)::int n from ff_measurement.page_opens')).n>0);
        assert.equal((await one("select count(*)::int n from ff_measurement.rate_limits where bucket='expired'")).n,0);
        assert.equal((await one("select count(*)::int n from ff_measurement.rate_limits where bucket='recent'")).n,1);
        assert.deepEqual((await query('select * from ff_measurement.milestones order by business_id,location_id,stage')).rows,milestonesBefore);
        assert.equal((await one('select count(*)::int n from public.feedback')).n,feedbackBefore);
        assert.deepEqual(await one('select * from cron.job'),{jobname:'ff-measurement-retention',schedule:'17 3 * * *',command:'select ff_measurement.cleanup()',jobid:1,active:false});
        await db.exec('commit');
        await query('delete from public.businesses where id=$1',[lateSetup.business.id]);
        assert.equal((await one('select complete_acquisition_signup() result')).result,null,'login never recreates a deliberately deleted business');
    }
    finally {
        await db.close();
    }
});
